# Generated by Django 5.2.7 on 2025-10-28 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='ativo',
            new_name='active',
        ),
    ]
